"$schema" = "https://raw.githubusercontent.com/HyDE-Project/HyDE/refs/heads/master/Configs/.local/share/hyde/schema/config.toml.json"

[hyprland-start]
bar = "bash -c 'sleep 1 && caelestia shell -d'"
notifications = ""

[hyprland]
browser = "zen-browser"
terminal = "ghostty"
bar = "hyprpanel"
# font = "JetBrainsMono Nerd Font"
monospace_font = "JetBrainsMono Nerd Font"


[wallpaper]
custom_paths = ["$HOME/Pictures/Wallpapers"]
