"$schema" = "https://raw.githubusercontent.com/HyDE-Project/HyDE/refs/heads/master/Configs/.local/share/hyde/schema/config.toml.json"

[hyprland_start]
notifications = ""
bar = "hyprpanel"

[hyprland]
browser = "zen-browser"
terminal = "ghostty"
bar = "hyprpanel"
# font = "JetBrainsMono Nerd Font"
monospace_font = "JetBrainsMono Nerd Font"


[wallpaper]
custom_paths = ["$HOME/Pictures/Wallpapers"]
