
# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█

# Set your monitor configuration here
# See https://wiki.hyprland.org/Configuring/Monitors/
# For a sample file, please refer to https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/hypr/monitors.t2
monitor = desc:Samsung Electric Company LS24C33xG H9TX301388, 1920x1080@100, -1920x0, 1
monitor = desc:AOC U34G3G3R3 QXVQ5JA000007, 3440x1440@165, 0x0, 1
monitor = desc:BOE Display 0x00000001, 2560x1440@144, 0x-1440, 1
monitor = desc:Thermotrex Corporation TL134ADXP01-0, 2560x1600@165, 0x0, 1.25
