# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

# Sourced from userprefs.conf
# See https://wiki.hyprland.org/Configuring/Window-Rules/

$&=override
windowrule = opacity 1 $& 1 $& 1 $&,match:class ^(.*)$

# modals
windowrule = float on, match:class ^(1password)$
windowrule = float on, match:class ^(org.kde.dolphin)$
windowrule = dim_around on, match:title ^(Quick Access — 1Password)$
windowrule = size 800 600, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = size 800 600, match:class ^(pavucontrol)$

windowrule = workspace 10, match:class ^(.*[Ss]potify.*)$ # Spotify

# HyprXEdge — fullscreen on Xeneon Edge touchscreen
windowrule = monitor HDMI-A-1, match:title ^(xeneon-edge)$
windowrule = no_blur true, match:title ^(xeneon-edge)$

# screen-share protection, toggled by $mainMod Shift Alt, S
source = ./noscreenshare.conf
