
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# See https://wiki.hyprland.org/Configuring for more information
dwindle {
    preserve_split = true
}

decoration {
    active_opacity = 1.0
    inactive_opacity = 1.0
}


# █░░ ▄▀█ █░█ █▄░█ █▀▀ █░█
# █▄▄ █▀█ █▄█ █░▀█ █▄▄ █▀█

exec-once = 1password --ozone-platform-hint=x11

# █ █▄░█ █▀█ █░█ ▀█▀
# █ █░▀█ █▀▀ █▄█ ░█░

input {
    follow_mouse = 2
#     kb_layout = us
#     follow_mouse = 1
    sensitivity = 0.3
    force_no_accel = 1
#     numlock_by_default = true

#     touchpad {
# # See https://wiki.hyprland.org/Configuring/Variables/#touchpad
#         natural_scroll = no
#     }
}

gestures {
# See https://wiki.hyprland.org/Configuring/Variables/#gestures
    workspace_swipe = true
    workspace_swipe_fingers = 3
}

decoration {
    blur {
        enabled = no
        size = 4
        passes = 1
    }
}
